com.agustin.tarati.core.domain.game.manager.GameManagerState
com.agustin.tarati.core.domain.ai.evaluator.EvaluationConfig
com.agustin.tarati.core.domain.ai.evaluator.BehaviorConfig
com.agustin.tarati.core.domain.ai.evaluator.MaterialWeights
com.agustin.tarati.core.domain.ai.evaluator.PositionalWeights
com.agustin.tarati.core.domain.ai.evaluator.SearchWeights
com.agustin.tarati.core.domain.ai.evaluator.TacticalWeights
com.agustin.tarati.core.domain.game.play.GameState
com.agustin.tarati.core.domain.game.play.StableHistoryList
com.agustin.tarati.core.domain.game.board.BoardOrientation
com.agustin.tarati.features.game.GameEvents