package com.agustin.tarati.core.domain.game.play

import androidx.compose.runtime.Immutable
import com.agustin.tarati.core.domain.game.board.BoardSymmetry
import com.agustin.tarati.core.domain.game.board.GameBoard.adjacencyMap
import com.agustin.tarati.core.domain.game.board.GameBoard.homeBases
import com.agustin.tarati.core.domain.game.board.Vertex
import com.agustin.tarati.core.domain.game.board.Vertex.Companion.parseVertex
import com.agustin.tarati.core.domain.game.pieces.opponent
import kotlinx.serialization.Serializable

/**
 * Representa un movimiento de una pieza desde [from] hasta [to].
 *
 * ## Por qué from/to son los parámetros primarios (no Pair)
 * kotlinx.serialization serializa exactamente el constructor primario;
 * exponer `from` y `to` directos produce un JSON plano y estable, sin
 * depender del serializer de `Pair` en un tipo central del protocolo y
 * de la persistencia.
 *
 * ## Compatibilidad de call sites
 * El constructor secundario `constructor(Pair<Vertex, Vertex>)` mantiene la
 * sintaxis existente `Move(A1 to B1)` en todo el código sin cambios.
 */
@Immutable
@Serializable
data class Move(
    val from: Vertex,
    val to: Vertex,
) {
    /**
     * Convenience constructor para la sintaxis `Move(A1 to B1)`.
     * Delega al constructor primario.
     */
    constructor(vertices: Pair<Vertex, Vertex>) : this(vertices.first, vertices.second)

    /**
     * Pair de vértices derivado de [from] y [to]. No forma parte del
     * constructor primario, por lo que kotlinx.serialization no lo incluye
     * en el payload.
     */
    val vertices: Pair<Vertex, Vertex> = from to to

    /**
     * Human-readable notation for this move.
     * - Normal move:               "B6-B1"
     * - Forced in-place promotion: "C12=R"  (Cob promoted to Rok in place)
     */
    val name: String
        get() = if (isPromotion()) "${from.name}$PROMOTION_SUFFIX" else "${from.name}$MOVE_SEPARATOR${to.name}"

    /**
     * Returns true if this move is a forced in-place promotion (from == to).
     * Promotion moves are generated by [GameState.getForcedPromotions] and applied
     * via [GameState.applyPromotion].
     */
    fun isPromotion(): Boolean = from == to

    /**
     * This move reflected across the board's bilateral axis of symmetry (see [BoardSymmetry]):
     * the same move toward the opposite side. A promotion (from == to) stays a promotion at the
     * mirrored vertex.
     */
    fun mirrored(): Move = Move(BoardSymmetry.mirror(from), BoardSymmetry.mirror(to))

    fun isCaptureMove(
        oldState: GameState,
        newState: GameState,
    ): Boolean {
        val capturedPieces = countFlipsByType(oldState, newState)
        return capturedPieces.first > 0 || capturedPieces.second > 0
    }

    /**
     * Counts flips (rok flips, cob flips) produced by this move, for sound and animation use.
     *
     * Promotion moves produce no flips.
     * For all other moves: counts adjacents of [to] that were NOT adjacent to [from] before
     * the move (pre-adjacency rule).
     */
    fun countFlipsByType(
        oldState: GameState,
        newState: GameState,
    ): Pair<Int, Int> {
        if (isPromotion()) return 0 to 0

        var rocFlips = 0
        var cobFlips = 0

        val originAdjacents = adjacencyMap[from]?.toSet() ?: emptySet()
        for (vertex in adjacencyMap[to] ?: emptyList()) {
            if (vertex in originAdjacents) continue
            val oldCob = oldState.cobs[vertex]
            val newCob = newState.cobs[vertex]
            if (oldCob != null && newCob != null && oldCob.color != newCob.color) {
                if (oldCob.isUpgraded) rocFlips++ else cobFlips++
            }
        }

        return Pair(rocFlips, cobFlips)
    }

    fun isUpgradeMove(
        oldState: GameState,
        newState: GameState,
    ): Boolean {
        // Forced in-place promotion: cob at 'from' becomes a rok without moving
        if (isPromotion()) {
            val oldCob = oldState.cobs[from] ?: return false
            val newCob = newState.cobs[from] ?: return false
            return !oldCob.isUpgraded && newCob.isUpgraded
        }

        val movingCob = oldState.cobs[from] ?: return false

        if (movingCob.isUpgraded) return false

        val enemyBase = homeBases[movingCob.color.opponent] ?: emptyList()
        if (to !in enemyBase) return false

        val newCob = newState.cobs[to]
        return newCob?.isUpgraded == true
    }

    companion object {
        const val MOVE_SEPARATOR: String = "-"

        /** Sufijo de la notación de promoción in-place ("C12=R"), producida por [name]. */
        const val PROMOTION_SUFFIX: String = "=R"

        /** Separador usado en partidas guardadas antes del cambio a ASCII. */
        const val LEGACY_SEPARATOR: String = "→"

        fun parseMoveHistory(moveHistory: String): List<Move> =
            if (moveHistory.isNotEmpty()) {
                moveHistory.split(",").map { moveStr ->
                    // Promoción in-place ("C12=R") → movimiento con from == to.
                    if (moveStr.endsWith(PROMOTION_SUFFIX)) {
                        val vertex = parseVertex(moveStr.removeSuffix(PROMOTION_SUFFIX))
                        Move(vertex, vertex)
                    } else {
                        // Acepta tanto "-" (actual) como "→" (partidas previas en BD)
                        val parts = moveStr.split(MOVE_SEPARATOR, LEGACY_SEPARATOR)
                        if (parts.size != 2) throw IllegalArgumentException("Invalid move format: $moveStr")
                        Move(parseVertex(parts[0]), parseVertex(parts[1]))
                    }
                }
            } else {
                emptyList()
            }
    }
}