package com.agustin.tarati.core.domain.game.play

import com.agustin.tarati.core.domain.game.board.GameBoard.adjacencyMap
import com.agustin.tarati.core.domain.game.board.GameBoard.homeBases
import com.agustin.tarati.core.domain.game.board.Vertex
import com.agustin.tarati.core.domain.game.board.Vertex.Companion.parseVertex
import androidx.compose.runtime.Immutable
import com.agustin.tarati.core.domain.game.pieces.opponent
import kotlinx.serialization.Serializable

/**
 * Representa un movimiento de una pieza desde [from] hasta [to].
 *
 * ## Por qué from/to son los parámetros primarios (no Pair)
 * `kotlin.Pair` implementa `java.io.Serializable` pero NO `Parcelable`.
 * Cuando `@Parcelize` encontraba `Pair<Vertex, Vertex>` como campo primario,
 * caía al fallback de Java serialization, que fallaba con
 * `NotSerializableException: Vertex` porque `Vertex` solo implementa
 * `Parcelable`. Al exponer `from` y `to` directamente, el plugin `@Parcelize`
 * los serializa como `Parcelable` nativo sin pasar por serialización Java.
 *
 * ## Compatibilidad de call sites
 * El constructor secundario `constructor(Pair<Vertex, Vertex>)` mantiene la
 * sintaxis existente `Move(A1 to B1)` en todo el código sin cambios.
 */
@Immutable
@Serializable
data class Move(
    val from: Vertex,
    val to: Vertex,
) {
    /**
     * Convenience constructor para la sintaxis `Move(A1 to B1)`.
     * Delega al constructor primario — no se parcela; `from` y `to` sí.
     */
    constructor(vertices: Pair<Vertex, Vertex>) : this(vertices.first, vertices.second)

    /**
     * Pair de vértices derivado de [from] y [to].
     * Marcado con `@IgnoredOnParcel` porque no forma parte del constructor
     * primario y no debe serializarse de forma independiente.
     */
    val vertices: Pair<Vertex, Vertex> = from to to

    /**
     * Human-readable notation for this move.
     * - Normal move:               "B6-B1"
     * - Forced in-place promotion: "C12=R"  (Cob promoted to Rok in place)
     */
    val name get() = if (isPromotion()) "${from.name}=R" else "${from.name}$MOVE_SEPARATOR${to.name}"

    /**
     * Returns true if this move is a forced in-place promotion (from == to).
     * Promotion moves are generated by [GameState.getForcedPromotions] and applied
     * via [GameState.applyPromotion].
     */
    fun isPromotion(): Boolean = from == to

    fun isCaptureMove(
        oldState: GameState,
        newState: GameState,
    ): Boolean {
        val capturedPieces = countFlipsByType(oldState, newState)
        return capturedPieces.first > 0 || capturedPieces.second > 0
    }

    /**
     * Counts flips (rok flips, cob flips) produced by this move, for sound and animation use.
     *
     * Promotion moves produce no flips.
     * For all other moves: counts adjacents of [to] that were NOT adjacent to [from] before
     * the move (pre-adjacency rule).
     */
    fun countFlipsByType(
        oldState: GameState,
        newState: GameState,
    ): Pair<Int, Int> {
        if (isPromotion()) return 0 to 0

        var rocFlips = 0
        var cobFlips = 0

        val originAdjacents = adjacencyMap[from]?.toSet() ?: emptySet()
        for (vertex in adjacencyMap[to] ?: emptyList()) {
            if (vertex in originAdjacents) continue
            val oldCob = oldState.cobs[vertex]
            val newCob = newState.cobs[vertex]
            if (oldCob != null && newCob != null && oldCob.color != newCob.color) {
                if (oldCob.isUpgraded) rocFlips++ else cobFlips++
            }
        }

        return Pair(rocFlips, cobFlips)
    }

    fun isUpgradeMove(
        oldState: GameState,
        newState: GameState,
    ): Boolean {
        // Forced in-place promotion: cob at 'from' becomes a rok without moving
        if (isPromotion()) {
            val oldCob = oldState.cobs[from] ?: return false
            val newCob = newState.cobs[from] ?: return false
            return !oldCob.isUpgraded && newCob.isUpgraded
        }

        val movingCob = oldState.cobs[from] ?: return false

        if (movingCob.isUpgraded) return false

        val enemyBase = homeBases[movingCob.color.opponent] ?: emptyList()
        if (to !in enemyBase) return false

        val newCob = newState.cobs[to]
        return newCob?.isUpgraded == true
    }

    companion object {
        const val MOVE_SEPARATOR = "-"

        /** Separador usado en partidas guardadas antes del cambio a ASCII. */
        const val LEGACY_SEPARATOR = "→"

        fun parseMoveHistory(moveHistory: String): List<Move> =
            if (moveHistory.isNotEmpty()) {
                moveHistory.split(",").map { moveStr ->
                    // Acepta tanto "-" (actual) como "→" (partidas previas en BD)
                    val parts = moveStr.split(MOVE_SEPARATOR, LEGACY_SEPARATOR)
                    if (parts.size != 2) throw IllegalArgumentException("Invalid move format: $moveStr")
                    val fromVertex = parseVertex(parts[0])
                    val toVertex = parseVertex(parts[1])
                    Move(fromVertex to toVertex)
                }
            } else {
                emptyList()
            }
    }
}